# data split

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df1 = pd.read_csv('dataset/9003_dataset.csv')

In [3]:
df1

,Latitude,Longitude,Type,Zone,location_type,if_optimal_zone,dist_to_optimal_point,traffic_count,Heavy_traffic,Distance to the nearest fast charger,Distance to the nearest destination charger,Fast_food,Fuel_station,Tourism,dist,z_str
0,-34.508903,144.842785,1,20,3,1,0.539601,14283,1,117.914230,0.022555,2,4,2,0.000706,90.262
1,-34.746497,146.550076,1,20,3,1,0.887491,29358,1,83.735856,25.326981,0,2,1,0.000424,148.545
2,-35.354863,145.725113,1,20,3,1,0.178044,15717,1,75.411076,71.534310,0,4,0,0.000659,110.000
3,-34.639541,143.564708,1,20,3,1,0.370967,8572,1,117.914230,47.392221,0,5,1,0.001037,66.709
4,-33.923735,147.203554,1,20,3,1,1.075135,21018,1,65.591754,88.407090,1,2,0,0.000800,261.980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,-28.237614,153.561853,5,10,2,1,3.054176,122842,1,43.304810,2.437959,13,11,4,0.000189,7.000
1910,-28.262766,153.570827,5,10,2,1,0.921810,137476,1,40.469801,0.830271,11,11,3,0.000479,5.514
1911,-28.333660,153.570229,5,10,2,1,8.231247,25108,1,32.596629,0.331032,3,3,1,0.000395,9.303
1912,-28.340455,153.565917,5,10,2,1,9.035906,25108,1,31.865917,1.162047,3,2,1,0.005467,13.336
1913,-28.637113,153.592305,5,10,2,1,0.052272,70779,1,1.310127,1.133005,13,5,7,0.000536,3.830

In [4]:
df2 = df1[df1['Type']!=4]
df2 = df2[df2['Type']!=5]
df2 = df2.drop(['Latitude', 'Longitude', 'Zone'], axis=1)

In [5]:
df2['Type'] = df2['Type'].apply(lambda x: 1 if x in [1, 2] else (2 if x == 3 else x))

In [6]:
y = df2['Type']
X = df2.drop('Type', axis=1)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# KNN

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=20)

knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"accuracy：{accuracy:.4f}")
print(class_report)

accuracy：0.9258
              precision    recall  f1-score   support

           1       0.95      0.94      0.95       220
           2       0.86      0.89      0.87        90

    accuracy                           0.93       310
   macro avg       0.91      0.91      0.91       310
weighted avg       0.93      0.93      0.93       310

D:\0Code\new_Anaconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

# MLR

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"accuracy：{accuracy:.4f}")
print(class_report)

accuracy：0.9032
              precision    recall  f1-score   support

           1       0.96      0.90      0.93       220
           2       0.79      0.90      0.84        90

    accuracy                           0.90       310
   macro avg       0.88      0.90      0.89       310
weighted avg       0.91      0.90      0.90       310

D:\0Code\new_Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier


rf_classifier = RandomForestClassifier(random_state=42,n_estimators=200,min_samples_split=5)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"accuracy：{accuracy:.4f}")
print(class_report)

accuracy：0.9677
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       220
           1       0.93      0.96      0.95        90

    accuracy                           0.97       310
   macro avg       0.96      0.96      0.96       310
weighted avg       0.97      0.97      0.97       310

# LightGBM

In [32]:
import lightgbm as lgb

lgb_classifier = lgb.LGBMClassifier(random_state=42)

lgb_classifier.fit(X_train, y_train)

y_pred = lgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"accuracy：{accuracy:.4f}")
print(class_report)

accuracy：0.9677
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       220
           1       0.93      0.96      0.95        90

    accuracy                           0.97       310
   macro avg       0.96      0.96      0.96       310
weighted avg       0.97      0.97      0.97       310

# Network

In [12]:
y_train = y_train - 1  # 将标签值减去1，从1、2、3转换为0、1、2
y_test = y_test - 1

In [13]:
import tensorflow as tf
from tensorflow import keras


# 创建神经网络模型
model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)),  # 输入层
    keras.layers.Dense(64, activation='relu'),  # 隐藏层1
    keras.layers.Dense(32, activation='relu'),  # 隐藏层2
    keras.layers.Dense(3, activation='softmax')  # 输出层，设置单元数量为3，使用softmax激活函数
])

# 编译模型并指定学习率
optimizer = keras.optimizers.Adam(learning_rate=0.05)  # 指定学习率
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 在训练集上训练模型
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

# 在测试集上进行预测
y_pred_prob = model.predict(X_test)
y_pred = tf.argmax(y_pred_prob, axis=1)  # 从概率中选择具有最高概率的类别

accuracy = accuracy_score(y_test, y_pred)

conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"accuracy：{accuracy:.4f}")
print(class_report)

Epoch 1/20
31/31 [==============================] - 1s 8ms/step - loss: 7087.6333 - accuracy: 0.8028 - val_loss: 3920.4956 - val_accuracy: 0.8790
Epoch 2/20
31/31 [==============================] - 0s 2ms/step - loss: 2796.5701 - accuracy: 0.8706 - val_loss: 3207.5593 - val_accuracy: 0.8911
Epoch 3/20
31/31 [==============================] - 0s 2ms/step - loss: 404.0809 - accuracy: 0.7968 - val_loss: 1.7274 - val_accuracy: 0.8629
Epoch 4/20
31/31 [==============================] - 0s 2ms/step - loss: 0.6675 - accuracy: 0.9050 - val_loss: 0.5512 - val_accuracy: 0.8750
Epoch 5/20
31/31 [==============================] - 0s 3ms/step - loss: 0.6768 - accuracy: 0.9070 - val_loss: 0.6848 - val_accuracy: 0.9073
Epoch 6/20
31/31 [==============================] - 0s 3ms/step - loss: 0.5069 - accuracy: 0.9130 - val_loss: 0.8491 - val_accuracy: 0.8911
Epoch 7/20
31/31 [==============================] - 0s 3ms/step - loss: 0.4109 - accuracy: 0.9130 - val_loss: 0.9530 - val_accuracy: 0.8911
Epoch 8/20
31/31 [==============================] - 0s 3ms/step - loss: 0.5746 - accuracy: 0.9151 - val_loss: 0.7420 - val_accuracy: 0.8911
Epoch 9/20
31/31 [==============================] - 0s 3ms/step - loss: 0.6622 - accuracy: 0.9110 - val_loss: 0.6019 - val_accuracy: 0.8992
Epoch 10/20
31/31 [==============================] - 0s 3ms/step - loss: 0.6005 - accuracy: 0.9100 - val_loss: 1.0020 - val_accuracy: 0.8790
Epoch 11/20
31/31 [==============================] - 0s 3ms/step - loss: 0.6865 - accuracy: 0.9070 - val_loss: 0.7365 - val_accuracy: 0.8871
Epoch 12/20
31/31 [==============================] - 0s 3ms/step - loss: 0.4763 - accuracy: 0.9039 - val_loss: 0.3998 - val_accuracy: 0.9113
Epoch 13/20
31/31 [==============================] - 0s 3ms/step - loss: 0.2983 - accuracy: 0.9181 - val_loss: 0.3441 - val_accuracy: 0.9113
Epoch 14/20
31/31 [==============================] - 0s 3ms/step - loss: 0.3215 - accuracy: 0.9141 - val_loss: 0.4768 - val_accuracy: 0.9113
Epoch 15/20
31/31 [==============================] - 0s 3ms/step - loss: 0.3258 - accuracy: 0.9110 - val_loss: 0.3332 - val_accuracy: 0.9032
Epoch 16/20
31/31 [==============================] - 0s 2ms/step - loss: 0.2910 - accuracy: 0.9171 - val_loss: 0.3027 - val_accuracy: 0.9073
Epoch 17/20
31/31 [==============================] - 0s 2ms/step - loss: 0.2831 - accuracy: 0.9151 - val_loss: 0.3005 - val_accuracy: 0.9113
Epoch 18/20
31/31 [==============================] - 0s 3ms/step - loss: 0.2706 - accuracy: 0.9161 - val_loss: 0.2967 - val_accuracy: 0.9113
Epoch 19/20
31/31 [==============================] - 0s 3ms/step - loss: 0.2723 - accuracy: 0.9171 - val_loss: 0.4104 - val_accuracy: 0.9113
Epoch 20/20
31/31 [==============================] - 0s 2ms/step - loss: 0.2803 - accuracy: 0.9201 - val_loss: 0.3056 - val_accuracy: 0.8952
10/10 [==============================] - 0s 1ms/step
accuracy：0.9129
              precision    recall  f1-score   support

           0       0.91      0.97      0.94       220
           1       0.92      0.77      0.84        90

    accuracy                           0.91       310
   macro avg       0.92      0.87      0.89       310
weighted avg       0.91      0.91      0.91       310

# evaluation and prediction

In [14]:
df3 = df1[df1["Type"]==4]

In [15]:
df3 = df3.drop(['Latitude', 'Longitude', 'Zone','Type'], axis=1)
df3

,location_type,if_optimal_zone,dist_to_optimal_point,traffic_count,Heavy_traffic,Distance to the nearest fast charger,Distance to the nearest destination charger,Fast_food,Fuel_station,Tourism,dist,z_str
1547,1,1,0.718934,313110,0,0.083751,0.203799,38,9,1,0.000136,7.296
1548,2,1,5.229272,235202,0,2.532164,4.871135,29,23,3,0.000138,12.597
1549,1,0,6.448421,52590,0,0.339709,0.139868,4,3,0,0.000340,18.539
1550,1,1,1.540638,63598,0,1.598620,1.190684,2,8,0,0.000096,58.303
1551,1,1,0.805492,371631,0,3.321339,0.701179,20,18,0,0.002216,7.512
...,...,...,...,...,...,...,...,...,...,...,...,...
1628,2,1,0.420047,47595,1,3.929844,0.427711,7,11,3,0.003949,7.337
1629,3,0,80.424056,16135,1,0.072353,0.215983,4,9,3,0.000259,867.000
1630,2,1,2.188731,118910,1,0.156988,0.154377,15,16,6,0.000315,189.362
1631,2,1,0.945710,48072,1,0.015156,0.239368,3,2,1,0.001274,496.676
1632,1,1,0.624985,39748,0,10.959596,0.556363,16,2,11,0.000555,1004.516

In [16]:
predictions = rf_classifier.predict(df3)
probabilities = rf_classifier.predict_proba(df3)

In [17]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [18]:
1-np.count_nonzero(predictions==3)/len(predictions)

1.0

In [19]:
temp = []
for i in probabilities:
    temp.append(max(i))
sum(temp)/len(temp)

0.9852325581395346

In [20]:
df4 = df1[(df1['Type'] == 4) | (df1['Type'] == 5)]

In [21]:
df5 = df4.drop(['Latitude', 'Longitude', 'Zone','Type'], axis=1)
df5

,location_type,if_optimal_zone,dist_to_optimal_point,traffic_count,Heavy_traffic,Distance to the nearest fast charger,Distance to the nearest destination charger,Fast_food,Fuel_station,Tourism,dist,z_str
1547,1,1,0.718934,313110,0,0.083751,0.203799,38,9,1,0.000136,7.296
1548,2,1,5.229272,235202,0,2.532164,4.871135,29,23,3,0.000138,12.597
1549,1,0,6.448421,52590,0,0.339709,0.139868,4,3,0,0.000340,18.539
1550,1,1,1.540638,63598,0,1.598620,1.190684,2,8,0,0.000096,58.303
1551,1,1,0.805492,371631,0,3.321339,0.701179,20,18,0,0.002216,7.512
...,...,...,...,...,...,...,...,...,...,...,...,...
1909,2,1,3.054176,122842,1,43.304810,2.437959,13,11,4,0.000189,7.000
1910,2,1,0.921810,137476,1,40.469801,0.830271,11,11,3,0.000479,5.514
1911,2,1,8.231247,25108,1,32.596629,0.331032,3,3,1,0.000395,9.303
1912,2,1,9.035906,25108,1,31.865917,1.162047,3,2,1,0.005467,13.336
1913,2,1,0.052272,70779,1,1.310127,1.133005,13,5,7,0.000536,3.830

In [22]:
# predictions = rf_classifier.predict(df5)
probabilities = rf_classifier.predict_proba(df5)

In [23]:
# 找到每行的最大值
max_values = np.max(probabilities, axis=1)
# 找出最大值大于0.9的行的索引
indexes = np.where(max_values >= 0.9)[0]

In [24]:
df_final = df4.iloc[indexes]

In [25]:
df_final

,Latitude,Longitude,Type,Zone,location_type,if_optimal_zone,dist_to_optimal_point,traffic_count,Heavy_traffic,Distance to the nearest fast charger,Distance to the nearest destination charger,Fast_food,Fuel_station,Tourism,dist,z_str
1547,-32.924818,151.751885,4,3,1,1,0.718934,313110,0,0.083751,0.203799,38,9,1,0.000136,7.296
1548,-33.278848,151.405538,4,10,2,1,5.229272,235202,0,2.532164,4.871135,29,23,3,0.000138,12.597
1549,-33.376148,151.473669,4,3,1,0,6.448421,52590,0,0.339709,0.139868,4,3,0,0.000340,18.539
1550,-33.796629,150.848800,4,3,1,1,1.540638,63598,0,1.598620,1.190684,2,8,0,0.000096,58.303
1551,-33.957864,151.139995,4,3,1,1,0.805492,371631,0,3.321339,0.701179,20,18,0,0.002216,7.512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,-28.237614,153.561853,5,10,2,1,3.054176,122842,1,43.304810,2.437959,13,11,4,0.000189,7.000
1910,-28.262766,153.570827,5,10,2,1,0.921810,137476,1,40.469801,0.830271,11,11,3,0.000479,5.514
1911,-28.333660,153.570229,5,10,2,1,8.231247,25108,1,32.596629,0.331032,3,3,1,0.000395,9.303
1912,-28.340455,153.565917,5,10,2,1,9.035906,25108,1,31.865917,1.162047,3,2,1,0.005467,13.336
1913,-28.637113,153.592305,5,10,2,1,0.052272,70779,1,1.310127,1.133005,13,5,7,0.000536,3.830